config/routes.rb
Rails.application.routes.draw do
  get "/tasks", to: "tasks#index"
  get  get "/tasks/:id", to: "tasks#show", as: :task
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end


  def destroy
    # @restaurant = Restaurant.find(params[:id])
    @task.destroy
    redirect_to tasks_path
  end

  def check!
    complete = @task.completed!
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/index.html.erb
<h1>my tasks</h1>
  <% @tasks.each do |task| %>
  <div class="container">
    <ul>
      <li><%= link_to task.title, task_path(task) %></li>
    </ul>
    </div>
<% end %>

app/views/tasks/show.html.erb
<div>
  <h1>task</h1>
  <ul>
    <li><%= @task.title %></li>
    <li><%= @task.details %></li>
    <li><input type="checkbox" <%= "checked" if @task.completed  %> id="task" name="checkbox"></li>



  </ul>
</div>

<%= link_to "Delete",
  task_path(@task),
  data: {turbo_method: :delete, turbo_confirm: "Are you REALLY sure?"}
%>

<%= link_to "Back home", tasks_path %>